server:
  port: 8001

spring:
  application:
    name: public

eureka:
  client:
    #    自己注册到EUREKA 上
    register-with-eureka: true
    #    需要去服务注册中心获取其他服务地址
    fetch-registry: true
    service-url:
      # eureka 注册中心的地址
      defaultZone:  http://localhost:7001/eureka/

